robot_name: tracebot

positions:
  camera:
    tilt: -1.0471975511965976
    z: 0.5

  left_arm_mount:
    x: -0.14411948870294738
    y: 0.31304381872725395
    z: 1.700434344106619
    roll: -0.04390803155229813
    pitch: -1.055093077121263
    yaw: 0.029461212366358548

  left_arm_ft_sensor:
    x: 0
    y: 0
    z: 0.04
    roll: 0
    pitch: 0
    yaw: 0

  left_arm_tcp:
    x: 0
    y: 0
    z: 0.28
    roll: 0
    pitch: 0
    yaw: 0

  right_arm_mount:
    x: 0.11471970927100625
    y: 0.30507837938290566
    z: 1.694411707886232
    roll: -0.01595933574536382
    pitch: 1.0303621249584036
    yaw: -0.007885036395912008

  right_arm_ft_sensor:
    x: 0
    y: 0
    z: 0
    roll: 0
    pitch: 0
    yaw: 0

  right_arm_tcp:
    x: 0
    y: 0
    z: 0.16
    roll: 0
    pitch: 0
    yaw: 0

  estimated_table:
    x: 0.02331898
    y: -0.21342195
    z: 0.79586235
    roll: 2.6246175945603496
    pitch: -0.00855385424264664
    yaw: 0.004863214695064039

parameters:
  left_arm:
    joint_limits_parameters_file: "$(find ur_description)/config/ur5/joint_limits.yaml"
    kinematics_parameters_file: "$(find tracebot_description)/config/tecnalia/ur_calibration/ur5_left.yaml"
    physical_parameters_file: "$(find ur_description)/config/ur5/physical_parameters.yaml"
    visual_parameters_file: "$(find ur_description)/config/ur5/visual_parameters.yaml"

  right_arm:
    joint_limits_parameters_file: "$(find ur_description)/config/ur5e/joint_limits.yaml"
    kinematics_parameters_file: "$(find tracebot_description)/config/tecnalia/ur_calibration/ur5e_right.yaml"
    physical_parameters_file: "$(find ur_description)/config/ur5e/physical_parameters.yaml"
    visual_parameters_file: "$(find ur_description)/config/ur5e/visual_parameters.yaml"

visualisation:
  left_arm_enabled: true
  right_arm_enabled: true
  robotiq_grippers_enabled: true
  mixed_grippers: false
  show_base_model: false
  load_scene: false
  load_estimated_scene: true
  table_width: 2
  table_depth: 1
  table_height: 0.05
  pump:
    enabled: true
    show_pump_holder: true
    mockup: true
    px: -0.038
    py: -0.282
    pz: -0.008
    rr: 0.003
    rp: -0.008
    ry: -0.035